/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IAgentBazaar {
  export type AgentListingStruct = {
    agentId: BigNumberish;
    isActive: boolean;
    category: string;
    basePrice: BigNumberish;
    skills: string[];
    supportedTrustModels: BigNumberish[];
    totalTasksCompleted: BigNumberish;
    totalEarnings: BigNumberish;
  };

  export type AgentListingStructOutput = [
    agentId: bigint,
    isActive: boolean,
    category: string,
    basePrice: bigint,
    skills: string[],
    supportedTrustModels: bigint[],
    totalTasksCompleted: bigint,
    totalEarnings: bigint
  ] & {
    agentId: bigint;
    isActive: boolean;
    category: string;
    basePrice: bigint;
    skills: string[];
    supportedTrustModels: bigint[];
    totalTasksCompleted: bigint;
    totalEarnings: bigint;
  };

  export type EscrowStruct = {
    taskId: BytesLike;
    amount: BigNumberish;
    clientAddress: AddressLike;
    agentId: BigNumberish;
    released: boolean;
    autoReleaseAt: BigNumberish;
  };

  export type EscrowStructOutput = [
    taskId: string,
    amount: bigint,
    clientAddress: string,
    agentId: bigint,
    released: boolean,
    autoReleaseAt: bigint
  ] & {
    taskId: string;
    amount: bigint;
    clientAddress: string;
    agentId: bigint;
    released: boolean;
    autoReleaseAt: bigint;
  };

  export type TaskStruct = {
    taskId: BytesLike;
    agentId: BigNumberish;
    clientAddress: AddressLike;
    skill: string;
    complexity: BigNumberish;
    description: string;
    filesUri: string;
    deadline: BigNumberish;
    price: BigNumberish;
    status: BigNumberish;
    resultUri: string;
    createdAt: BigNumberish;
    completedAt: BigNumberish;
  };

  export type TaskStructOutput = [
    taskId: string,
    agentId: bigint,
    clientAddress: string,
    skill: string,
    complexity: bigint,
    description: string,
    filesUri: string,
    deadline: bigint,
    price: bigint,
    status: bigint,
    resultUri: string,
    createdAt: bigint,
    completedAt: bigint
  ] & {
    taskId: string;
    agentId: bigint;
    clientAddress: string;
    skill: string;
    complexity: bigint;
    description: string;
    filesUri: string;
    deadline: bigint;
    price: bigint;
    status: bigint;
    resultUri: string;
    createdAt: bigint;
    completedAt: bigint;
  };
}

export interface AgentBazaarInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AUTO_RELEASE_TIMEOUT"
      | "BPS_DENOMINATOR"
      | "CANCELLATION_TIMEOUT"
      | "MARKETPLACE_FEE_BPS"
      | "acceptTask"
      | "autoReleaseEscrow"
      | "cancelTask"
      | "completeTask"
      | "createTask"
      | "disputeTask"
      | "getAccumulatedFees"
      | "getAgentListing"
      | "getEscrow"
      | "getTask"
      | "getTasksByAgent"
      | "getTasksByClient"
      | "identityRegistry"
      | "listAgent"
      | "owner"
      | "renounceOwnership"
      | "reputationRegistry"
      | "transferOwnership"
      | "updateAgentListing"
      | "usdc"
      | "validateAndRelease"
      | "validationRegistry"
      | "withdrawMarketplaceFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentListed"
      | "AgentListingUpdated"
      | "EscrowReleased"
      | "MarketplaceFeesWithdrawn"
      | "OwnershipTransferred"
      | "TaskAccepted"
      | "TaskCancelled"
      | "TaskCompleted"
      | "TaskCreated"
      | "TaskDisputed"
      | "TaskValidated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AUTO_RELEASE_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CANCELLATION_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MARKETPLACE_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "autoReleaseEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeTask",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [BigNumberish, string, BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccumulatedFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getTask", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getTasksByAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTasksByClient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listAgent",
    values: [BigNumberish, string, BigNumberish, string[], BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputationRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgentListing",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "validateAndRelease",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "validationRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawMarketplaceFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "AUTO_RELEASE_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CANCELLATION_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MARKETPLACE_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "acceptTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "autoReleaseEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccumulatedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTasksByAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTasksByClient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgentListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateAndRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validationRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawMarketplaceFees",
    data: BytesLike
  ): Result;
}

export namespace AgentListedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    category: string,
    basePrice: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    category: string,
    basePrice: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    category: string;
    basePrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentListingUpdatedEvent {
  export type InputTuple = [agentId: BigNumberish, isActive: boolean];
  export type OutputTuple = [agentId: bigint, isActive: boolean];
  export interface OutputObject {
    agentId: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    amount: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [taskId: string, amount: bigint, recipient: string];
  export interface OutputObject {
    taskId: string;
    amount: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketplaceFeesWithdrawnEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskAcceptedEvent {
  export type InputTuple = [taskId: BytesLike, agentId: BigNumberish];
  export type OutputTuple = [taskId: string, agentId: bigint];
  export interface OutputObject {
    taskId: string;
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [taskId: BytesLike];
  export type OutputTuple = [taskId: string];
  export interface OutputObject {
    taskId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCompletedEvent {
  export type InputTuple = [taskId: BytesLike, resultUri: string];
  export type OutputTuple = [taskId: string, resultUri: string];
  export interface OutputObject {
    taskId: string;
    resultUri: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    agentId: BigNumberish,
    clientAddress: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    agentId: bigint,
    clientAddress: string,
    price: bigint
  ];
  export interface OutputObject {
    taskId: string;
    agentId: bigint;
    clientAddress: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskDisputedEvent {
  export type InputTuple = [taskId: BytesLike];
  export type OutputTuple = [taskId: string];
  export interface OutputObject {
    taskId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskValidatedEvent {
  export type InputTuple = [taskId: BytesLike, approved: boolean];
  export type OutputTuple = [taskId: string, approved: boolean];
  export interface OutputObject {
    taskId: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentBazaar extends BaseContract {
  connect(runner?: ContractRunner | null): AgentBazaar;
  waitForDeployment(): Promise<this>;

  interface: AgentBazaarInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AUTO_RELEASE_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  CANCELLATION_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  MARKETPLACE_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  acceptTask: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  autoReleaseEscrow: TypedContractMethod<
    [taskId: BytesLike],
    [void],
    "nonpayable"
  >;

  cancelTask: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  completeTask: TypedContractMethod<
    [taskId: BytesLike, resultUri: string],
    [void],
    "nonpayable"
  >;

  createTask: TypedContractMethod<
    [
      agentId: BigNumberish,
      skill: string,
      complexity: BigNumberish,
      description: string,
      filesUri: string,
      deadline: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  disputeTask: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  getAccumulatedFees: TypedContractMethod<[], [bigint], "view">;

  getAgentListing: TypedContractMethod<
    [agentId: BigNumberish],
    [IAgentBazaar.AgentListingStructOutput],
    "view"
  >;

  getEscrow: TypedContractMethod<
    [taskId: BytesLike],
    [IAgentBazaar.EscrowStructOutput],
    "view"
  >;

  getTask: TypedContractMethod<
    [taskId: BytesLike],
    [IAgentBazaar.TaskStructOutput],
    "view"
  >;

  getTasksByAgent: TypedContractMethod<
    [agentId: BigNumberish],
    [IAgentBazaar.TaskStructOutput[]],
    "view"
  >;

  getTasksByClient: TypedContractMethod<
    [clientAddress: AddressLike],
    [IAgentBazaar.TaskStructOutput[]],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  listAgent: TypedContractMethod<
    [
      agentId: BigNumberish,
      category: string,
      basePrice: BigNumberish,
      skills: string[],
      trustModels: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputationRegistry: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAgentListing: TypedContractMethod<
    [agentId: BigNumberish, isActive: boolean],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  validateAndRelease: TypedContractMethod<
    [taskId: BytesLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  validationRegistry: TypedContractMethod<[], [string], "view">;

  withdrawMarketplaceFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AUTO_RELEASE_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CANCELLATION_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MARKETPLACE_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptTask"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "autoReleaseEscrow"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeTask"
  ): TypedContractMethod<
    [taskId: BytesLike, resultUri: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      skill: string,
      complexity: BigNumberish,
      description: string,
      filesUri: string,
      deadline: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeTask"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAccumulatedFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgentListing"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [IAgentBazaar.AgentListingStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [IAgentBazaar.EscrowStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [IAgentBazaar.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTasksByAgent"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [IAgentBazaar.TaskStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTasksByClient"
  ): TypedContractMethod<
    [clientAddress: AddressLike],
    [IAgentBazaar.TaskStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "listAgent"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      category: string,
      basePrice: BigNumberish,
      skills: string[],
      trustModels: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputationRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAgentListing"
  ): TypedContractMethod<
    [agentId: BigNumberish, isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "validateAndRelease"
  ): TypedContractMethod<
    [taskId: BytesLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validationRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawMarketplaceFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AgentListed"
  ): TypedContractEvent<
    AgentListedEvent.InputTuple,
    AgentListedEvent.OutputTuple,
    AgentListedEvent.OutputObject
  >;
  getEvent(
    key: "AgentListingUpdated"
  ): TypedContractEvent<
    AgentListingUpdatedEvent.InputTuple,
    AgentListingUpdatedEvent.OutputTuple,
    AgentListingUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;
  getEvent(
    key: "MarketplaceFeesWithdrawn"
  ): TypedContractEvent<
    MarketplaceFeesWithdrawnEvent.InputTuple,
    MarketplaceFeesWithdrawnEvent.OutputTuple,
    MarketplaceFeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TaskAccepted"
  ): TypedContractEvent<
    TaskAcceptedEvent.InputTuple,
    TaskAcceptedEvent.OutputTuple,
    TaskAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskCompleted"
  ): TypedContractEvent<
    TaskCompletedEvent.InputTuple,
    TaskCompletedEvent.OutputTuple,
    TaskCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskDisputed"
  ): TypedContractEvent<
    TaskDisputedEvent.InputTuple,
    TaskDisputedEvent.OutputTuple,
    TaskDisputedEvent.OutputObject
  >;
  getEvent(
    key: "TaskValidated"
  ): TypedContractEvent<
    TaskValidatedEvent.InputTuple,
    TaskValidatedEvent.OutputTuple,
    TaskValidatedEvent.OutputObject
  >;

  filters: {
    "AgentListed(uint256,string,uint256)": TypedContractEvent<
      AgentListedEvent.InputTuple,
      AgentListedEvent.OutputTuple,
      AgentListedEvent.OutputObject
    >;
    AgentListed: TypedContractEvent<
      AgentListedEvent.InputTuple,
      AgentListedEvent.OutputTuple,
      AgentListedEvent.OutputObject
    >;

    "AgentListingUpdated(uint256,bool)": TypedContractEvent<
      AgentListingUpdatedEvent.InputTuple,
      AgentListingUpdatedEvent.OutputTuple,
      AgentListingUpdatedEvent.OutputObject
    >;
    AgentListingUpdated: TypedContractEvent<
      AgentListingUpdatedEvent.InputTuple,
      AgentListingUpdatedEvent.OutputTuple,
      AgentListingUpdatedEvent.OutputObject
    >;

    "EscrowReleased(bytes32,uint256,address)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;

    "MarketplaceFeesWithdrawn(address,uint256)": TypedContractEvent<
      MarketplaceFeesWithdrawnEvent.InputTuple,
      MarketplaceFeesWithdrawnEvent.OutputTuple,
      MarketplaceFeesWithdrawnEvent.OutputObject
    >;
    MarketplaceFeesWithdrawn: TypedContractEvent<
      MarketplaceFeesWithdrawnEvent.InputTuple,
      MarketplaceFeesWithdrawnEvent.OutputTuple,
      MarketplaceFeesWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TaskAccepted(bytes32,uint256)": TypedContractEvent<
      TaskAcceptedEvent.InputTuple,
      TaskAcceptedEvent.OutputTuple,
      TaskAcceptedEvent.OutputObject
    >;
    TaskAccepted: TypedContractEvent<
      TaskAcceptedEvent.InputTuple,
      TaskAcceptedEvent.OutputTuple,
      TaskAcceptedEvent.OutputObject
    >;

    "TaskCancelled(bytes32)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskCompleted(bytes32,string)": TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
    TaskCompleted: TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;

    "TaskCreated(bytes32,uint256,address,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskDisputed(bytes32)": TypedContractEvent<
      TaskDisputedEvent.InputTuple,
      TaskDisputedEvent.OutputTuple,
      TaskDisputedEvent.OutputObject
    >;
    TaskDisputed: TypedContractEvent<
      TaskDisputedEvent.InputTuple,
      TaskDisputedEvent.OutputTuple,
      TaskDisputedEvent.OutputObject
    >;

    "TaskValidated(bytes32,bool)": TypedContractEvent<
      TaskValidatedEvent.InputTuple,
      TaskValidatedEvent.OutputTuple,
      TaskValidatedEvent.OutputObject
    >;
    TaskValidated: TypedContractEvent<
      TaskValidatedEvent.InputTuple,
      TaskValidatedEvent.OutputTuple,
      TaskValidatedEvent.OutputObject
    >;
  };
}
