/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IdentityRegistry__factory } from "./IdentityRegistry__factory";
export { ReputationRegistry__factory } from "./ReputationRegistry__factory";
export { ValidationRegistry__factory } from "./ValidationRegistry__factory";
