/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IERC8004Reputation {
  export type ProofOfPaymentStruct = {
    fromAddress: AddressLike;
    toAddress: AddressLike;
    chainId: BigNumberish;
    txHash: BytesLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
    signature: BytesLike;
  };

  export type ProofOfPaymentStructOutput = [
    fromAddress: string,
    toAddress: string,
    chainId: bigint,
    txHash: string,
    amount: bigint,
    timestamp: bigint,
    signature: string
  ] & {
    fromAddress: string;
    toAddress: string;
    chainId: bigint;
    txHash: string;
    amount: bigint;
    timestamp: bigint;
    signature: string;
  };

  export type FeedbackStruct = {
    feedbackId: BigNumberish;
    agentId: BigNumberish;
    clientAddress: AddressLike;
    taskId: BytesLike;
    score: BigNumberish;
    skill: string;
    context: string;
    feedbackUri: string;
    contentHash: BytesLike;
    proofOfPayment: IERC8004Reputation.ProofOfPaymentStruct;
    timestamp: BigNumberish;
  };

  export type FeedbackStructOutput = [
    feedbackId: bigint,
    agentId: bigint,
    clientAddress: string,
    taskId: string,
    score: bigint,
    skill: string,
    context: string,
    feedbackUri: string,
    contentHash: string,
    proofOfPayment: IERC8004Reputation.ProofOfPaymentStructOutput,
    timestamp: bigint
  ] & {
    feedbackId: bigint;
    agentId: bigint;
    clientAddress: string;
    taskId: string;
    score: bigint;
    skill: string;
    context: string;
    feedbackUri: string;
    contentHash: string;
    proofOfPayment: IERC8004Reputation.ProofOfPaymentStructOutput;
    timestamp: bigint;
  };
}

export interface IERC8004ReputationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeClientFeedback"
      | "calculateAverageScore"
      | "calculateScoreBySkill"
      | "getFeedbackByTask"
      | "getFeedbackHistory"
      | "getTotalFeedbackCount"
      | "hasClientProvidedFeedback"
      | "registerFeedback"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeedbackAuthorized"
      | "FeedbackRegistered"
      | "PaymentProofVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeClientFeedback",
    values: [BigNumberish, AddressLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateAverageScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateScoreBySkill",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedbackByTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedbackHistory",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalFeedbackCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClientProvidedFeedback",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerFeedback",
    values: [
      BigNumberish,
      BytesLike,
      BigNumberish,
      string,
      string,
      string,
      BytesLike,
      IERC8004Reputation.ProofOfPaymentStruct
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeClientFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateAverageScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateScoreBySkill",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedbackByTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedbackHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalFeedbackCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasClientProvidedFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerFeedback",
    data: BytesLike
  ): Result;
}

export namespace FeedbackAuthorizedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    clientAddress: AddressLike,
    taskId: BytesLike,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    clientAddress: string,
    taskId: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    clientAddress: string;
    taskId: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeedbackRegisteredEvent {
  export type InputTuple = [
    feedbackId: BigNumberish,
    agentId: BigNumberish,
    clientAddress: AddressLike,
    taskId: BytesLike,
    score: BigNumberish
  ];
  export type OutputTuple = [
    feedbackId: bigint,
    agentId: bigint,
    clientAddress: string,
    taskId: string,
    score: bigint
  ];
  export interface OutputObject {
    feedbackId: bigint;
    agentId: bigint;
    clientAddress: string;
    taskId: string;
    score: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentProofVerifiedEvent {
  export type InputTuple = [
    txHash: BytesLike,
    fromAddress: AddressLike,
    toAddress: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    txHash: string,
    fromAddress: string,
    toAddress: string,
    amount: bigint
  ];
  export interface OutputObject {
    txHash: string;
    fromAddress: string;
    toAddress: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IERC8004Reputation extends BaseContract {
  connect(runner?: ContractRunner | null): IERC8004Reputation;
  waitForDeployment(): Promise<this>;

  interface: IERC8004ReputationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeClientFeedback: TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      taskId: BytesLike,
      expiresAt: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  calculateAverageScore: TypedContractMethod<
    [agentId: BigNumberish],
    [[bigint, bigint] & { weightedScore: bigint; totalFeedbacks: bigint }],
    "view"
  >;

  calculateScoreBySkill: TypedContractMethod<
    [agentId: BigNumberish, skill: string],
    [[bigint, bigint] & { averageScore: bigint; count: bigint }],
    "view"
  >;

  getFeedbackByTask: TypedContractMethod<
    [taskId: BytesLike],
    [IERC8004Reputation.FeedbackStructOutput],
    "view"
  >;

  getFeedbackHistory: TypedContractMethod<
    [agentId: BigNumberish, offset: BigNumberish, limit: BigNumberish],
    [IERC8004Reputation.FeedbackStructOutput[]],
    "view"
  >;

  getTotalFeedbackCount: TypedContractMethod<
    [agentId: BigNumberish],
    [bigint],
    "view"
  >;

  hasClientProvidedFeedback: TypedContractMethod<
    [taskId: BytesLike, clientAddress: AddressLike],
    [boolean],
    "view"
  >;

  registerFeedback: TypedContractMethod<
    [
      agentId: BigNumberish,
      taskId: BytesLike,
      score: BigNumberish,
      skill: string,
      context: string,
      feedbackUri: string,
      contentHash: BytesLike,
      proofOfPayment: IERC8004Reputation.ProofOfPaymentStruct
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeClientFeedback"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      taskId: BytesLike,
      expiresAt: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateAverageScore"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [[bigint, bigint] & { weightedScore: bigint; totalFeedbacks: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateScoreBySkill"
  ): TypedContractMethod<
    [agentId: BigNumberish, skill: string],
    [[bigint, bigint] & { averageScore: bigint; count: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeedbackByTask"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [IERC8004Reputation.FeedbackStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeedbackHistory"
  ): TypedContractMethod<
    [agentId: BigNumberish, offset: BigNumberish, limit: BigNumberish],
    [IERC8004Reputation.FeedbackStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalFeedbackCount"
  ): TypedContractMethod<[agentId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasClientProvidedFeedback"
  ): TypedContractMethod<
    [taskId: BytesLike, clientAddress: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerFeedback"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      taskId: BytesLike,
      score: BigNumberish,
      skill: string,
      context: string,
      feedbackUri: string,
      contentHash: BytesLike,
      proofOfPayment: IERC8004Reputation.ProofOfPaymentStruct
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "FeedbackAuthorized"
  ): TypedContractEvent<
    FeedbackAuthorizedEvent.InputTuple,
    FeedbackAuthorizedEvent.OutputTuple,
    FeedbackAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "FeedbackRegistered"
  ): TypedContractEvent<
    FeedbackRegisteredEvent.InputTuple,
    FeedbackRegisteredEvent.OutputTuple,
    FeedbackRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentProofVerified"
  ): TypedContractEvent<
    PaymentProofVerifiedEvent.InputTuple,
    PaymentProofVerifiedEvent.OutputTuple,
    PaymentProofVerifiedEvent.OutputObject
  >;

  filters: {
    "FeedbackAuthorized(uint256,address,bytes32,uint256)": TypedContractEvent<
      FeedbackAuthorizedEvent.InputTuple,
      FeedbackAuthorizedEvent.OutputTuple,
      FeedbackAuthorizedEvent.OutputObject
    >;
    FeedbackAuthorized: TypedContractEvent<
      FeedbackAuthorizedEvent.InputTuple,
      FeedbackAuthorizedEvent.OutputTuple,
      FeedbackAuthorizedEvent.OutputObject
    >;

    "FeedbackRegistered(uint256,uint256,address,bytes32,uint8)": TypedContractEvent<
      FeedbackRegisteredEvent.InputTuple,
      FeedbackRegisteredEvent.OutputTuple,
      FeedbackRegisteredEvent.OutputObject
    >;
    FeedbackRegistered: TypedContractEvent<
      FeedbackRegisteredEvent.InputTuple,
      FeedbackRegisteredEvent.OutputTuple,
      FeedbackRegisteredEvent.OutputObject
    >;

    "PaymentProofVerified(bytes32,address,address,uint256)": TypedContractEvent<
      PaymentProofVerifiedEvent.InputTuple,
      PaymentProofVerifiedEvent.OutputTuple,
      PaymentProofVerifiedEvent.OutputObject
    >;
    PaymentProofVerified: TypedContractEvent<
      PaymentProofVerifiedEvent.InputTuple,
      PaymentProofVerifiedEvent.OutputTuple,
      PaymentProofVerifiedEvent.OutputObject
    >;
  };
}
