/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IERC8004Identity {
  export type AgentInfoStruct = {
    agentId: BigNumberish;
    agentAddress: AddressLike;
    agentDomain: string;
    contentHash: BytesLike;
    registrationTime: BigNumberish;
    isActive: boolean;
  };

  export type AgentInfoStructOutput = [
    agentId: bigint,
    agentAddress: string,
    agentDomain: string,
    contentHash: string,
    registrationTime: bigint,
    isActive: boolean
  ] & {
    agentId: bigint;
    agentAddress: string;
    agentDomain: string;
    contentHash: string;
    registrationTime: bigint;
    isActive: boolean;
  };
}

export interface IERC8004IdentityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAgent"
      | "getAgentByAddress"
      | "hasAgent"
      | "listAgents"
      | "registerAgent"
      | "setAgentStatus"
      | "totalAgents"
      | "updateAgentCard"
      | "verifyAgentCard"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentCardUpdated"
      | "AgentRegistered"
      | "AgentStatusChanged"
      | "AgentTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentByAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listAgents",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgentCard",
    values: [BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAgentCard",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listAgents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgentCard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAgentCard",
    data: BytesLike
  ): Result;
}

export namespace AgentCardUpdatedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    newAgentDomain: string,
    newContentHash: BytesLike
  ];
  export type OutputTuple = [
    agentId: bigint,
    newAgentDomain: string,
    newContentHash: string
  ];
  export interface OutputObject {
    agentId: bigint;
    newAgentDomain: string;
    newContentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    agentAddress: AddressLike,
    agentDomain: string,
    contentHash: BytesLike
  ];
  export type OutputTuple = [
    agentId: bigint,
    agentAddress: string,
    agentDomain: string,
    contentHash: string
  ];
  export interface OutputObject {
    agentId: bigint;
    agentAddress: string;
    agentDomain: string;
    contentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentStatusChangedEvent {
  export type InputTuple = [agentId: BigNumberish, isActive: boolean];
  export type OutputTuple = [agentId: bigint, isActive: boolean];
  export interface OutputObject {
    agentId: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentTransferredEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [agentId: bigint, from: string, to: string];
  export interface OutputObject {
    agentId: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IERC8004Identity extends BaseContract {
  connect(runner?: ContractRunner | null): IERC8004Identity;
  waitForDeployment(): Promise<this>;

  interface: IERC8004IdentityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAgent: TypedContractMethod<
    [agentId: BigNumberish],
    [IERC8004Identity.AgentInfoStructOutput],
    "view"
  >;

  getAgentByAddress: TypedContractMethod<
    [agentAddress: AddressLike],
    [IERC8004Identity.AgentInfoStructOutput],
    "view"
  >;

  hasAgent: TypedContractMethod<[agentAddress: AddressLike], [boolean], "view">;

  listAgents: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [IERC8004Identity.AgentInfoStructOutput[]],
    "view"
  >;

  registerAgent: TypedContractMethod<
    [agentDomain: string, contentHash: BytesLike, tokenURI: string],
    [bigint],
    "nonpayable"
  >;

  setAgentStatus: TypedContractMethod<
    [agentId: BigNumberish, isActive: boolean],
    [void],
    "nonpayable"
  >;

  totalAgents: TypedContractMethod<[], [bigint], "view">;

  updateAgentCard: TypedContractMethod<
    [agentId: BigNumberish, newAgentDomain: string, newContentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyAgentCard: TypedContractMethod<
    [agentId: BigNumberish, agentCardJSON: string],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [IERC8004Identity.AgentInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentByAddress"
  ): TypedContractMethod<
    [agentAddress: AddressLike],
    [IERC8004Identity.AgentInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasAgent"
  ): TypedContractMethod<[agentAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "listAgents"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [IERC8004Identity.AgentInfoStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [agentDomain: string, contentHash: BytesLike, tokenURI: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentStatus"
  ): TypedContractMethod<
    [agentId: BigNumberish, isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalAgents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateAgentCard"
  ): TypedContractMethod<
    [agentId: BigNumberish, newAgentDomain: string, newContentHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAgentCard"
  ): TypedContractMethod<
    [agentId: BigNumberish, agentCardJSON: string],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AgentCardUpdated"
  ): TypedContractEvent<
    AgentCardUpdatedEvent.InputTuple,
    AgentCardUpdatedEvent.OutputTuple,
    AgentCardUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentStatusChanged"
  ): TypedContractEvent<
    AgentStatusChangedEvent.InputTuple,
    AgentStatusChangedEvent.OutputTuple,
    AgentStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "AgentTransferred"
  ): TypedContractEvent<
    AgentTransferredEvent.InputTuple,
    AgentTransferredEvent.OutputTuple,
    AgentTransferredEvent.OutputObject
  >;

  filters: {
    "AgentCardUpdated(uint256,string,bytes32)": TypedContractEvent<
      AgentCardUpdatedEvent.InputTuple,
      AgentCardUpdatedEvent.OutputTuple,
      AgentCardUpdatedEvent.OutputObject
    >;
    AgentCardUpdated: TypedContractEvent<
      AgentCardUpdatedEvent.InputTuple,
      AgentCardUpdatedEvent.OutputTuple,
      AgentCardUpdatedEvent.OutputObject
    >;

    "AgentRegistered(uint256,address,string,bytes32)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentStatusChanged(uint256,bool)": TypedContractEvent<
      AgentStatusChangedEvent.InputTuple,
      AgentStatusChangedEvent.OutputTuple,
      AgentStatusChangedEvent.OutputObject
    >;
    AgentStatusChanged: TypedContractEvent<
      AgentStatusChangedEvent.InputTuple,
      AgentStatusChangedEvent.OutputTuple,
      AgentStatusChangedEvent.OutputObject
    >;

    "AgentTransferred(uint256,address,address)": TypedContractEvent<
      AgentTransferredEvent.InputTuple,
      AgentTransferredEvent.OutputTuple,
      AgentTransferredEvent.OutputObject
    >;
    AgentTransferred: TypedContractEvent<
      AgentTransferredEvent.InputTuple,
      AgentTransferredEvent.OutputTuple,
      AgentTransferredEvent.OutputObject
    >;
  };
}
