/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC8004Reputation,
  IERC8004ReputationInterface,
} from "../../../contracts/interfaces/IERC8004Reputation";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "clientAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "taskId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "expiresAt",
        type: "uint256",
      },
    ],
    name: "FeedbackAuthorized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "feedbackId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "clientAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "taskId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "score",
        type: "uint8",
      },
    ],
    name: "FeedbackRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "txHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "fromAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "toAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "PaymentProofVerified",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "clientAddress",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "taskId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "expiresAt",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "authorizeClientFeedback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
    ],
    name: "calculateAverageScore",
    outputs: [
      {
        internalType: "uint256",
        name: "weightedScore",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalFeedbacks",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "skill",
        type: "string",
      },
    ],
    name: "calculateScoreBySkill",
    outputs: [
      {
        internalType: "uint256",
        name: "averageScore",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "count",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "taskId",
        type: "bytes32",
      },
    ],
    name: "getFeedbackByTask",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "feedbackId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "agentId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "clientAddress",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "taskId",
            type: "bytes32",
          },
          {
            internalType: "uint8",
            name: "score",
            type: "uint8",
          },
          {
            internalType: "string",
            name: "skill",
            type: "string",
          },
          {
            internalType: "string",
            name: "context",
            type: "string",
          },
          {
            internalType: "string",
            name: "feedbackUri",
            type: "string",
          },
          {
            internalType: "bytes32",
            name: "contentHash",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "address",
                name: "fromAddress",
                type: "address",
              },
              {
                internalType: "address",
                name: "toAddress",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "chainId",
                type: "uint256",
              },
              {
                internalType: "bytes32",
                name: "txHash",
                type: "bytes32",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "timestamp",
                type: "uint256",
              },
              {
                internalType: "bytes",
                name: "signature",
                type: "bytes",
              },
            ],
            internalType: "struct IERC8004Reputation.ProofOfPayment",
            name: "proofOfPayment",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
        ],
        internalType: "struct IERC8004Reputation.Feedback",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "offset",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "limit",
        type: "uint256",
      },
    ],
    name: "getFeedbackHistory",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "feedbackId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "agentId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "clientAddress",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "taskId",
            type: "bytes32",
          },
          {
            internalType: "uint8",
            name: "score",
            type: "uint8",
          },
          {
            internalType: "string",
            name: "skill",
            type: "string",
          },
          {
            internalType: "string",
            name: "context",
            type: "string",
          },
          {
            internalType: "string",
            name: "feedbackUri",
            type: "string",
          },
          {
            internalType: "bytes32",
            name: "contentHash",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "address",
                name: "fromAddress",
                type: "address",
              },
              {
                internalType: "address",
                name: "toAddress",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "chainId",
                type: "uint256",
              },
              {
                internalType: "bytes32",
                name: "txHash",
                type: "bytes32",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "timestamp",
                type: "uint256",
              },
              {
                internalType: "bytes",
                name: "signature",
                type: "bytes",
              },
            ],
            internalType: "struct IERC8004Reputation.ProofOfPayment",
            name: "proofOfPayment",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
        ],
        internalType: "struct IERC8004Reputation.Feedback[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
    ],
    name: "getTotalFeedbackCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "taskId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "clientAddress",
        type: "address",
      },
    ],
    name: "hasClientProvidedFeedback",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "taskId",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "score",
        type: "uint8",
      },
      {
        internalType: "string",
        name: "skill",
        type: "string",
      },
      {
        internalType: "string",
        name: "context",
        type: "string",
      },
      {
        internalType: "string",
        name: "feedbackUri",
        type: "string",
      },
      {
        internalType: "bytes32",
        name: "contentHash",
        type: "bytes32",
      },
      {
        components: [
          {
            internalType: "address",
            name: "fromAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "toAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "chainId",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "txHash",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct IERC8004Reputation.ProofOfPayment",
        name: "proofOfPayment",
        type: "tuple",
      },
    ],
    name: "registerFeedback",
    outputs: [
      {
        internalType: "uint256",
        name: "feedbackId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC8004Reputation__factory {
  static readonly abi = _abi;
  static createInterface(): IERC8004ReputationInterface {
    return new Interface(_abi) as IERC8004ReputationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC8004Reputation {
    return new Contract(address, _abi, runner) as unknown as IERC8004Reputation;
  }
}
