/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IdentityRegistry } from "./IdentityRegistry";
export type { ReputationRegistry } from "./ReputationRegistry";
export type { ValidationRegistry } from "./ValidationRegistry";
