/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IERC8004Validation {
  export type ValidationRequestStruct = {
    requestId: BigNumberish;
    agentId: BigNumberish;
    taskId: BytesLike;
    requester: AddressLike;
    validationType: BigNumberish;
    validationRequestUri: string;
    contentHash: BytesLike;
    validatorAddress: AddressLike;
    timestamp: BigNumberish;
    status: BigNumberish;
  };

  export type ValidationRequestStructOutput = [
    requestId: bigint,
    agentId: bigint,
    taskId: string,
    requester: string,
    validationType: bigint,
    validationRequestUri: string,
    contentHash: string,
    validatorAddress: string,
    timestamp: bigint,
    status: bigint
  ] & {
    requestId: bigint;
    agentId: bigint;
    taskId: string;
    requester: string;
    validationType: bigint;
    validationRequestUri: string;
    contentHash: string;
    validatorAddress: string;
    timestamp: bigint;
    status: bigint;
  };

  export type ValidationResponseStruct = {
    requestId: BigNumberish;
    validatorAddress: AddressLike;
    approved: boolean;
    validationResponseUri: string;
    evidenceHash: BytesLike;
    timestamp: BigNumberish;
    rewardClaimed: boolean;
  };

  export type ValidationResponseStructOutput = [
    requestId: bigint,
    validatorAddress: string,
    approved: boolean,
    validationResponseUri: string,
    evidenceHash: string,
    timestamp: bigint,
    rewardClaimed: boolean
  ] & {
    requestId: bigint;
    validatorAddress: string;
    approved: boolean;
    validationResponseUri: string;
    evidenceHash: string;
    timestamp: bigint;
    rewardClaimed: boolean;
  };

  export type ValidatorStakeStruct = {
    validator: AddressLike;
    stakedAmount: BigNumberish;
    correctValidations: BigNumberish;
    incorrectValidations: BigNumberish;
    slashedAmount: BigNumberish;
  };

  export type ValidatorStakeStructOutput = [
    validator: string,
    stakedAmount: bigint,
    correctValidations: bigint,
    incorrectValidations: bigint,
    slashedAmount: bigint
  ] & {
    validator: string;
    stakedAmount: bigint;
    correctValidations: bigint;
    incorrectValidations: bigint;
    slashedAmount: bigint;
  };
}

export interface ValidationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_VALIDATOR_STAKE"
      | "SLASH_PERCENTAGE"
      | "VALIDATION_REWARD"
      | "calculateApprovalRate"
      | "disputeValidation"
      | "getValidationRequest"
      | "getValidationResponse"
      | "getValidationsByAgent"
      | "getValidationsByTask"
      | "getValidatorReputation"
      | "identityRegistry"
      | "owner"
      | "registerValidatorStake"
      | "renounceOwnership"
      | "requestValidation"
      | "resolveDispute"
      | "submitValidationResponse"
      | "transferOwnership"
      | "withdrawValidatorStake"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeRaised"
      | "DisputeResolved"
      | "OwnershipTransferred"
      | "ValidationRequested"
      | "ValidationResponseSubmitted"
      | "ValidatorRewarded"
      | "ValidatorSlashed"
      | "ValidatorStaked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_VALIDATOR_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SLASH_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VALIDATION_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateApprovalRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeValidation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidationRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidationResponse",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidationsByAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidationsByTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidatorReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerValidatorStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestValidation",
    values: [
      BigNumberish,
      BytesLike,
      BigNumberish,
      string,
      BytesLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "submitValidationResponse",
    values: [BigNumberish, boolean, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawValidatorStake",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_VALIDATOR_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SLASH_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VALIDATION_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateApprovalRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidationRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidationResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidationsByAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidationsByTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidatorReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerValidatorStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitValidationResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawValidatorStake",
    data: BytesLike
  ): Result;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [requestId: BigNumberish, disputer: AddressLike];
  export type OutputTuple = [requestId: bigint, disputer: string];
  export interface OutputObject {
    requestId: bigint;
    disputer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    validatorWasCorrect: boolean
  ];
  export type OutputTuple = [requestId: bigint, validatorWasCorrect: boolean];
  export interface OutputObject {
    requestId: bigint;
    validatorWasCorrect: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidationRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    agentId: BigNumberish,
    taskId: BytesLike,
    validationType: BigNumberish,
    validatorAddress: AddressLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    agentId: bigint,
    taskId: string,
    validationType: bigint,
    validatorAddress: string
  ];
  export interface OutputObject {
    requestId: bigint;
    agentId: bigint;
    taskId: string;
    validationType: bigint;
    validatorAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidationResponseSubmittedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    validatorAddress: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    requestId: bigint,
    validatorAddress: string,
    approved: boolean
  ];
  export interface OutputObject {
    requestId: bigint;
    validatorAddress: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorRewardedEvent {
  export type InputTuple = [validator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [validator: string, amount: bigint];
  export interface OutputObject {
    validator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorSlashedEvent {
  export type InputTuple = [validator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [validator: string, amount: bigint];
  export interface OutputObject {
    validator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorStakedEvent {
  export type InputTuple = [validator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [validator: string, amount: bigint];
  export interface OutputObject {
    validator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ValidationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ValidationRegistry;
  waitForDeployment(): Promise<this>;

  interface: ValidationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_VALIDATOR_STAKE: TypedContractMethod<[], [bigint], "view">;

  SLASH_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  VALIDATION_REWARD: TypedContractMethod<[], [bigint], "view">;

  calculateApprovalRate: TypedContractMethod<
    [agentId: BigNumberish],
    [[bigint, bigint] & { approvedCount: bigint; totalCount: bigint }],
    "view"
  >;

  disputeValidation: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getValidationRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [IERC8004Validation.ValidationRequestStructOutput],
    "view"
  >;

  getValidationResponse: TypedContractMethod<
    [requestId: BigNumberish],
    [IERC8004Validation.ValidationResponseStructOutput],
    "view"
  >;

  getValidationsByAgent: TypedContractMethod<
    [agentId: BigNumberish],
    [IERC8004Validation.ValidationRequestStructOutput[]],
    "view"
  >;

  getValidationsByTask: TypedContractMethod<
    [taskId: BytesLike],
    [IERC8004Validation.ValidationRequestStructOutput[]],
    "view"
  >;

  getValidatorReputation: TypedContractMethod<
    [validator: AddressLike],
    [IERC8004Validation.ValidatorStakeStructOutput],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerValidatorStake: TypedContractMethod<[], [void], "payable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestValidation: TypedContractMethod<
    [
      agentId: BigNumberish,
      taskId: BytesLike,
      validationType: BigNumberish,
      validationRequestUri: string,
      contentHash: BytesLike,
      validatorAddress: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [requestId: BigNumberish, validatorWasCorrect: boolean],
    [void],
    "nonpayable"
  >;

  submitValidationResponse: TypedContractMethod<
    [
      requestId: BigNumberish,
      approved: boolean,
      validationResponseUri: string,
      evidenceHash: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawValidatorStake: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_VALIDATOR_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLASH_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VALIDATION_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateApprovalRate"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [[bigint, bigint] & { approvedCount: bigint; totalCount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "disputeValidation"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getValidationRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [IERC8004Validation.ValidationRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidationResponse"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [IERC8004Validation.ValidationResponseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidationsByAgent"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [IERC8004Validation.ValidationRequestStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidationsByTask"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [IERC8004Validation.ValidationRequestStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidatorReputation"
  ): TypedContractMethod<
    [validator: AddressLike],
    [IERC8004Validation.ValidatorStakeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerValidatorStake"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestValidation"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      taskId: BytesLike,
      validationType: BigNumberish,
      validationRequestUri: string,
      contentHash: BytesLike,
      validatorAddress: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [requestId: BigNumberish, validatorWasCorrect: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitValidationResponse"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      approved: boolean,
      validationResponseUri: string,
      evidenceHash: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawValidatorStake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ValidationRequested"
  ): TypedContractEvent<
    ValidationRequestedEvent.InputTuple,
    ValidationRequestedEvent.OutputTuple,
    ValidationRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ValidationResponseSubmitted"
  ): TypedContractEvent<
    ValidationResponseSubmittedEvent.InputTuple,
    ValidationResponseSubmittedEvent.OutputTuple,
    ValidationResponseSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorRewarded"
  ): TypedContractEvent<
    ValidatorRewardedEvent.InputTuple,
    ValidatorRewardedEvent.OutputTuple,
    ValidatorRewardedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorSlashed"
  ): TypedContractEvent<
    ValidatorSlashedEvent.InputTuple,
    ValidatorSlashedEvent.OutputTuple,
    ValidatorSlashedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorStaked"
  ): TypedContractEvent<
    ValidatorStakedEvent.InputTuple,
    ValidatorStakedEvent.OutputTuple,
    ValidatorStakedEvent.OutputObject
  >;

  filters: {
    "DisputeRaised(uint256,address)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(uint256,bool)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ValidationRequested(uint256,uint256,bytes32,uint8,address)": TypedContractEvent<
      ValidationRequestedEvent.InputTuple,
      ValidationRequestedEvent.OutputTuple,
      ValidationRequestedEvent.OutputObject
    >;
    ValidationRequested: TypedContractEvent<
      ValidationRequestedEvent.InputTuple,
      ValidationRequestedEvent.OutputTuple,
      ValidationRequestedEvent.OutputObject
    >;

    "ValidationResponseSubmitted(uint256,address,bool)": TypedContractEvent<
      ValidationResponseSubmittedEvent.InputTuple,
      ValidationResponseSubmittedEvent.OutputTuple,
      ValidationResponseSubmittedEvent.OutputObject
    >;
    ValidationResponseSubmitted: TypedContractEvent<
      ValidationResponseSubmittedEvent.InputTuple,
      ValidationResponseSubmittedEvent.OutputTuple,
      ValidationResponseSubmittedEvent.OutputObject
    >;

    "ValidatorRewarded(address,uint256)": TypedContractEvent<
      ValidatorRewardedEvent.InputTuple,
      ValidatorRewardedEvent.OutputTuple,
      ValidatorRewardedEvent.OutputObject
    >;
    ValidatorRewarded: TypedContractEvent<
      ValidatorRewardedEvent.InputTuple,
      ValidatorRewardedEvent.OutputTuple,
      ValidatorRewardedEvent.OutputObject
    >;

    "ValidatorSlashed(address,uint256)": TypedContractEvent<
      ValidatorSlashedEvent.InputTuple,
      ValidatorSlashedEvent.OutputTuple,
      ValidatorSlashedEvent.OutputObject
    >;
    ValidatorSlashed: TypedContractEvent<
      ValidatorSlashedEvent.InputTuple,
      ValidatorSlashedEvent.OutputTuple,
      ValidatorSlashedEvent.OutputObject
    >;

    "ValidatorStaked(address,uint256)": TypedContractEvent<
      ValidatorStakedEvent.InputTuple,
      ValidatorStakedEvent.OutputTuple,
      ValidatorStakedEvent.OutputObject
    >;
    ValidatorStaked: TypedContractEvent<
      ValidatorStakedEvent.InputTuple,
      ValidatorStakedEvent.OutputTuple,
      ValidatorStakedEvent.OutputObject
    >;
  };
}
